#!/bin/bash
python3 -c $'import os,functools as f\nW=os.getenv(\"WATER\",\"\")\nS=os.getenv(\"STIR\",\"\")\nA=\"water\"\nB=\"stir\"\nC=\"bestchol\"\nconv=lambda s,a:f.reduce(lambda x,ch:x*len(a)+a.index(ch),[ch for ch in s if ch in a],0)\nn=conv(W,A)+conv(S,B)\nL=len(C)\nout=\"\"\nwhile n>0:\n n,r=divmod(n,L)\n out=C[r]+out\nprint(out or C[0])'
