#!/bin/bash
python3 -c 'import os;import functools as f;A="water";B="stir";C="bestchol";g=lambda s,a:f.reduce(lambda x,ch:x*len(a)+a.index(ch),[c for c in s if c in a],0);n=g(os.getenv("WATER",""),A)+g(os.getenv("STIR",""),B);h=lambda x:(x==0)and C[0]or h(x//len(C))+C[x%len(C)];print(h(n))'
